module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  testPathIgnorePatterns: [
    '/node_modules/',
    'src/tests/modules/auth/',
    'src/tests/modules/comment/',
    'src/tests/modules/message/',
    'src/tests/modules/notification/',
    'src/tests/modules/post/',
    'src/tests/modules/scholarship/',
    'src/tests/modules/user/',
    'src/tests/shared/',
    'src/tests/integration/',
  ],
  moduleFileExtensions: ['ts', 'js', 'json'],
  collectCoverageFrom: [
    'src/**/*.{ts,js}',
    '!src/**/*.d.ts',
    '!src/tests/**',
  ],
  coverageDirectory: 'coverage',
  verbose: true,
  setupFiles: ['<rootDir>/jest.setup.js'],
};
