/**
 * Post validation constraints
 */
export const POST_VALIDATION = {
  TITLE_MIN_LENGTH: 5,
  TITLE_MAX_LENGTH: 120,
  CONTENT_MAX_LENGTH: 5000,
  ALT_TEXT_MAX_LENGTH: 150,
  MAX_IMAGES: 3,
  MAX_PAGINATION_LIMIT: 100,
  DEFAULT_PAGINATION_LIMIT: 10,
} as const;

/**
 * Post error messages
 */
export const POST_ERROR = {
  NOT_FOUND: 'POST_NOT_FOUND',
  UNAUTHORIZED: 'POST_UNAUTHORIZED',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND_OR_INACTIVE',
} as const;
